services:
  syscall-dig:
    build:
      context: .
    privileged: true
    volumes:
      - ./test.py:/src/cmd/test/syscall_dig/test.py:ro
      - ./inputs.json:/syscall-dig-inputs.json:ro
      - ./requirements.txt:/requirements.txt:ro
      - pip-cache:/root/.cache/pip
      - python-packages:/var/sandbox/sandbox-python/usr/local/lib/python3.11/dist-packages
    working_dir: /src
    command:
      - sh
      - -c
      - >-
        install-python-deps &&
        ALLOWED_SYSCALLS="$$(seq -s, 0 499)"
        python3 cmd/test/syscall_dig/test.py &&
        exec go run cmd/test/syscall_dig/main.go

volumes:
  pip-cache:
  python-packages:
